### ISSUE TITLE
Allow filtering of virtual machines by datacenter, cluster or host names

### ISSUE THREAD

**Issue by abhi1693** [saltstack/salt-ext-modules-vmware#254]
`vmware_vm.list` currently returns a list of Virtual machines for the entire vCentre. The issue here is that I have more than 10000 machines and running automation tasks by cluster is too tedious as each VM is queried using `vmware_vm.info` to match it with the cluster and datacenter name in the loop. This takes several hours to finish even though I need to update only 25 Virtual machines from my cluster.

One argument could be made here to only provide permission to the cluster that I need. However, I really do need access to the vCenter completely as the automation tasks run on each cluster at different times and we manage these by the vCenter instances as a whole.

On `vmware_vm.list` optional parameters as `datacenter_name`, `cluster_name` and `host_name` should be added to provide more flexibility and narrowing down the result.

**Comment by waynew** [comment]
I think that's entirely valid 👍 I like the associated fix, too!
